"""Add customer ownership to vehicles

Revision ID: 754af73bfd6f
Revises: 1d75bbd4063f
Create Date: 2026-09-09 15:02:36.623935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754af73bfd6f'
down_revision: Union[str, Sequence[str], None] = '1d75bbd4063f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'users', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'customer_id')
    # ### end Alembic commands ###
